name: CI

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-10.15, platform: x64, cxx: clang++, cc: clang }

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      PLATFORM: ${{ matrix.config.platform }}
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DYLD_PRINT_LIBRARIES : true

    steps:
      - uses: actions/checkout@v2

      - name: Environment
        if: matrix.config.vs
        shell: bash
        run: echo "/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin" >> $GITHUB_PATH

      - name: Fix intrin.h file
        if: matrix.config.vs
        shell: powershell
        run: build/intrin.ps1
              
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            bin/Release_${{matrix.config.platform}}
            build/obj
          key: ${{matrix.config.os}}-${{matrix.config.platform}}-${{hashFiles('src/CppParser/*')}}-v7

      - name: Setup
        shell: bash
        run: |
          build/build.sh generate -platform $PLATFORM
          build/build.sh download_llvm -platform $PLATFORM

      - name: Restore
        shell: bash
        run: build/build.sh restore -platform $PLATFORM

      - name: Build
        shell: bash
        run: build/build.sh -platform $PLATFORM -build_only

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: cppsharp-${{ matrix.config.os }}-${{ matrix.config.platform }}-${{ matrix.config.cc }}
          retention-days: 5
          path: |
            bin/**
            build/gen/**
            build/obj/**
            build/make/**
